---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5e7e06c1276eef0012d9293c/webhook/forestry
sections:
- type: document
  path: content/find-a-therapist.md
  label: Tharapists
  templates:
  - showcase
- type: directory
  path: content/posts
  label: Post
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: content
  label: Page
  create: all
  match: "**/*"
  exclude: "{posts/**,_index.md,blog/_index.md,overview.md,showcase.md}"
  templates:
  - page
- type: document
  path: data/header.yml
  label: Header
  templates:
  - header
- type: document
  path: data/footer.yml
  label: Footer
  templates:
  - footer
- type: document
  path: data/social.json
  label: Social Links
  templates:
  - social
- type: document
  path: content/_index.md
  label: Home
  templates:
  - home
- type: document
  path: content/overview.md
  label: Overview
  templates:
  - overview
- type: document
  path: content/contact.md
  label: Contact
  templates:
  - contact
- type: document
  path: content/dues.md
  label: Dues
  templates:
  - dues
- type: document
  path: content/blog/_index.md
  label: Blog
  templates:
  - blog
- type: document
  path: config.yaml
  label: Global Site Config
  templates:
  - config
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.72.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.72.0
